# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: almatoolbox-default-linux

variables:
- group: smart-city-iot-platform-placeholder

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $JAVA_HOME'

#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'rm -rf /azp/_work/100/s'

#- task: VariableSetTask@3
#  inputs:
#    variableName: 'JAVA_HOME_8'
#    value: '/usr/lib/jvm/java-8-openjdk-amd64/'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonarqube-sicurezza'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'smart-city-iot-platform'
    cliProjectName: 'smart-city-iot-platform'
    cliSources: '.'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install -DskipTests -Ddockerfile.skip=false -Dlicense.skip'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

#- task: ArtifactoryMaven@2
#  inputs:
#    mavenPomFile: 'pom.xml'
#    goals: 'clean install -DskipTests -Ddockerfile.skip=false'
#    artifactoryResolverService: 'Jfrog-Giotto-IoT'
#    targetResolveReleaseRepo: 'remote-repos'
#    targetResolveSnapshotRepo: 'remote-repos'

- task: SonarQubeAnalyze@5
  inputs:
    jdkversion: 'JAVA_HOME'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'